[keyboard]
bindings = [
    # Scrollback
    { key = "PageUp",   mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
    { key = "PageDown", mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
    { key = "Home",     mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
    { key = "End",      mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
    { key = "K",        mods = "Command",       mode = "~Vi|~Search", action = "ReceiveChar" },

    # Searching
    { key = "F",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
    { key = "F",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
    { key = "B",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
    { key = "B",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },

    # Copy/Paste
    #{ key = "Paste",    action = "ReceiveChar" },
    #{ key = "Copy",     action = "ReceiveChar" },
    #{ key = "V",        mods = "Control|Shift", mode = "~Vi",         action = "ReceiveChar" },
    #{ key = "V",        mods = "Command",                          action = "ReceiveChar" },
    #{ key = "C",        mods = "Control|Shift",                    action = "ReceiveChar" },
    #{ key = "C",        mods = "Command",                          action = "ReceiveChar" },
    #{ key = "C",        mods = "Control|Shift", mode = "Vi|~Search", action = "ReceiveChar" },
    #{ key = "C",        mods = "Command",       mode = "Vi|~Search", action = "ReceiveChar" },
    #{ key = "Insert",   mods = "Shift",                            action = "ReceiveChar" },
    
    # Disable Alt+Enter
    { key = "Enter", mods = "Alt", action = "ReceiveChar" }
]

[mouse]
bindings = [
    { mouse = "Right", action = "ReceiveChar" }
]
